/**
 * Questions prédéfinies — thème : le code (programmation, dev, tech).
 * Réponses en minuscules pour la comparaison côté serveur.
 */

export interface PredefinedQuestion {
  text: string;
  answer: string;
}

export const PREDEFINED_QUESTIONS: PredefinedQuestion[] = [
  { text: "Quelle structure de données utilise une approche LIFO (Last In, First Out) ?", answer: "pile" },
  { text: "En Python, comment s'appelle le constructeur d'une classe ?", answer: "__init__" },
  { text: "Quel mot-clé en JavaScript permet de déclarer une variable constante ?", answer: "const" },
  { text: "En HTML, quelle balise crée un lien hypertexte ?", answer: "a" },
  { text: "Quelle méthode HTTP est utilisée pour récupérer des données sans effet de bord ?", answer: "get" },
  { text: "En CSS, quelle propriété change la couleur du texte ?", answer: "color" },
  { text: "Quel langage a été créé par James Gosling chez Sun Microsystems ?", answer: "java" },
  { text: "En SQL, quel mot-clé permet de filtrer les lignes d'une requête ?", answer: "where" },
  { text: "Quelle structure de données associe des clés à des valeurs ?", answer: "dictionnaire" },
  { text: "En Git, quelle commande crée une nouvelle branche ?", answer: "git branch" },
  { text: "Quel symbole en JavaScript représente l'égalité stricte (valeur et type) ?", answer: "===" },
  { text: "En React, quel hook permet de gérer un état local dans un composant ?", answer: "usestate" },
  { text: "Quel protocole est utilisé pour les pages web sécurisées (HTTPS) ?", answer: "tls" },
  { text: "En base de données, quel type de jointure garde toutes les lignes de la table de gauche ?", answer: "left join" },
  { text: "Quel outil en ligne de commande permet de gérer les paquets Node.js ?", answer: "npm" },
  { text: "Quel mot-clé Python permet de définir une fonction ?", answer: "def" },
  { text: "En JavaScript, quelle structure permet d'itérer sur les éléments d'un tableau ?", answer: "for" },
  { text: "Quel format de données utilise des paires clé-valeur en texte ?", answer: "json" },
  { text: "En Git, quelle commande enregistre les modifications dans l'historique ?", answer: "commit" },
  { text: "Quelle propriété CSS permet de centrer un élément horizontalement avec margin ?", answer: "auto" },
  { text: "Quel langage de requête est utilisé pour les bases de données relationnelles ?", answer: "sql" },
  { text: "En HTML5, quelle balise représente un en-tête de page ou de section ?", answer: "header" },
  { text: "Quel design pattern assure qu'une classe n'a qu'une seule instance ?", answer: "singleton" },
  { text: "En TypeScript, quel mot-clé permet de définir un type personnalisé ?", answer: "interface" },
  { text: "Quelle méthode JavaScript convertit une chaîne en nombre entier ?", answer: "parseint" },
  { text: "Quel protocole permet de transférer des fichiers (FTP) ?", answer: "ftp" },
  { text: "En React, quel hook exécute un effet après le rendu ?", answer: "useeffect" },
  { text: "Quelle structure de données suit le principe FIFO (First In, First Out) ?", answer: "file" },
  { text: "Quel mot-clé en Java permet l'héritage d'une classe ?", answer: "extends" },
  { text: "En CSS, quelle unité est relative à la taille de police de l'élément racine ?", answer: "rem" },
  { text: "Quelle méthode HTTP envoie des données pour créer une ressource ?", answer: "post" },
  { text: "Quel outil permet de versionner du code en équipe (Git, SVN...) ?", answer: "git" },
  { text: "En Python, quelle structure permet de stocker des éléments non modifiables ?", answer: "tuple" },
  { text: "Quel symbole en regex signifie 'un ou plusieurs' ?", answer: "+" },
  { text: "Quelle propriété CSS masque le débordement du contenu ?", answer: "overflow" },
  { text: "En base de données, quel mot-clé supprime toutes les lignes d'une table ?", answer: "delete" },
  { text: "Quel langage est souvent utilisé pour le machine learning (librairie pandas) ?", answer: "python" },
  { text: "Quelle balise HTML insère une image ?", answer: "img" },
  { text: "En JavaScript, quelle valeur représente l'absence intentionnelle de valeur ?", answer: "null" },
  { text: "Quel design pattern permet de notifier des observateurs lors d'un changement ?", answer: "observer" },
  { text: "En Git, quelle commande récupère les modifications du dépôt distant ?", answer: "pull" },
  { text: "Quelle propriété CSS définit l'ordre d'empilement des éléments ?", answer: "z-index" },
  { text: "Quel mot-clé SQL permet de trier les résultats ?", answer: "order by" },
  { text: "En HTML, quelle balise crée un conteneur générique en bloc ?", answer: "div" },
  { text: "Quel paradigme de programmation utilise des fonctions comme valeurs ?", answer: "fonctionnel" },
  { text: "Quelle méthode JavaScript ajoute un élément à la fin d'un tableau ?", answer: "push" },
  { text: "En CSS, quelle propriété permet d'arrondir les coins ?", answer: "border-radius" },
  { text: "Quel mot-clé en C/Java permet de sortir d'une boucle ?", answer: "break" },
  { text: "Quelle structure de données organise les nœuds en arbre ?", answer: "arbre" },
  { text: "En REST, quel code HTTP signifie 'créé' (201) ?", answer: "201" },
  { text: "Quel langage compile en JavaScript (TypeScript, CoffeeScript...) ?", answer: "typescript" },
  { text: "En Python, comment s'appelle la fonction qui affiche du texte ?", answer: "print" },
  { text: "Quelle propriété CSS permet de disposer des éléments en grille ?", answer: "grid" },
  { text: "Quel mot-clé JavaScript déclare une variable avec portée de bloc ?", answer: "let" },
  { text: "En HTML, quelle balise crée un paragraphe ?", answer: "p" },
  { text: "Quelle méthode JavaScript retourne la longueur d'un tableau ?", answer: "length" },
  { text: "En Git, quelle commande envoie les commits vers le dépôt distant ?", answer: "push" },
  { text: "Quel mot-clé SQL permet de regrouper des lignes ?", answer: "group by" },
  { text: "En CSS, quelle propriété définit l'espace entre les bordures des cellules ?", answer: "border-spacing" },
  { text: "Quel langage utilise des accolades pour délimiter les blocs ?", answer: "c" },
  { text: "En Python, quel opérateur donne le reste d'une division ?", answer: "%" },
  { text: "Quelle structure permet de stocker plusieurs valeurs dans une seule variable ?", answer: "tableau" },
  { text: "En JavaScript, quelle fonction exécute du code après un délai ?", answer: "settimeout" },
  { text: "Quel code HTTP signifie 'page non trouvée' ?", answer: "404" },
  { text: "En SQL, quel mot-clé évite les doublons dans les résultats ?", answer: "distinct" },
  { text: "Quelle propriété CSS affiche un élément en ligne ?", answer: "inline" },
  { text: "Quel mot-clé Python lance une exception ?", answer: "raise" },
  { text: "En React, quel hook mémorise une valeur entre les rendus ?", answer: "usememo" },
  { text: "Quel format de balises est utilisé pour structurer une page web ?", answer: "html" },
  { text: "En base de données, quel type est un entier auto-incrémenté ?", answer: "serial" },
  { text: "Quelle méthode JavaScript joint les éléments d'un tableau en chaîne ?", answer: "join" },
  { text: "Quel design pattern crée des objets sans préciser leur classe exacte ?", answer: "factory" },
  { text: "En CSS, quelle propriété rend le texte en gras ?", answer: "font-weight" },
  { text: "Quel mot-clé Java indique qu'une méthode ne retourne rien ?", answer: "void" },
  { text: "En Python, quel mot-clé gère les exceptions ?", answer: "try" },
  { text: "Quelle méthode HTTP met à jour une ressource existante ?", answer: "put" },
  { text: "Quel outil exécute du JavaScript côté serveur ?", answer: "node" },
  { text: "En HTML, quelle balise crée une liste non ordonnée ?", answer: "ul" },
  { text: "Quelle propriété CSS cache un élément tout en gardant sa place ?", answer: "visibility" },
  { text: "Quel mot-clé SQL ajoute des lignes dans une table ?", answer: "insert" },
  { text: "En JavaScript, quel type représente vrai ou faux ?", answer: "boolean" },
  { text: "Quel langage a été créé par Guido van Rossum ?", answer: "python" },
  { text: "En Git, quelle commande bascule sur une branche ?", answer: "checkout" },
  { text: "Quelle unité CSS vaut 1/100 de la hauteur du viewport ?", answer: "vh" },
  { text: "Quel symbole en JavaScript représente l'égalité non stricte ?", answer: "==" },
  { text: "En React, quelle fonction crée un élément virtuel ?", answer: "createelement" },
  { text: "Quel protocole permet de résoudre un nom de domaine en IP ?", answer: "dns" },
  { text: "En Python, quel mot-clé définit une classe ?", answer: "class" },
  { text: "Quelle propriété CSS positionne un élément en absolu ?", answer: "absolute" },
  { text: "Quel mot-clé SQL modifie les données d'une table ?", answer: "update" },
  { text: "En JavaScript, quelle méthode crée une copie superficielle d'un tableau ?", answer: "slice" },
  { text: "Quel design pattern encapsule une requête comme objet ?", answer: "command" },
  { text: "En HTML5, quelle balise contient du code ou des données ?", answer: "code" },
  { text: "Quelle méthode JavaScript supprime le dernier élément d'un tableau ?", answer: "pop" },
  { text: "Quel code HTTP signifie 'accès non autorisé' ?", answer: "401" },
  { text: "En CSS, quelle propriété espace les lettres ?", answer: "letter-spacing" },
  { text: "Quel mot-clé Java indique une constante ?", answer: "final" },
  { text: "En base de données, quel type stocke du texte long ?", answer: "text" },
  { text: "Quelle structure de contrôle répète du code tant qu'une condition est vraie ?", answer: "while" },
  { text: "Quel outil formate et vérifie le code JavaScript/TypeScript ?", answer: "prettier" },
  { text: "En React, quel hook gère les effets de bord ?", answer: "useeffect" },
  { text: "Quel langage de style décrit la présentation d'une page HTML ?", answer: "css" },
  { text: "En Git, quelle commande affiche l'historique des commits ?", answer: "log" },
  { text: "Quelle méthode JavaScript transforme chaque élément d'un tableau ?", answer: "map" },
  { text: "Quel mot-clé SQL compte le nombre de lignes ?", answer: "count" },
  { text: "En Python, quelle fonction retourne le type d'un objet ?", answer: "type" },
  { text: "Quelle propriété CSS centre le texte ?", answer: "text-align" },
  { text: "Quel symbole en regex signifie 'zéro ou un' ?", answer: "?" },
  { text: "En JavaScript, quel mot-clé appelle une fonction parente ?", answer: "super" },
  { text: "Quel design pattern compose des objets en arbre ?", answer: "composite" },
  { text: "En HTML, quelle balise crée un titre de niveau 1 ?", answer: "h1" },
  { text: "Quelle méthode HTTP supprime une ressource ?", answer: "delete" },
  { text: "Quel langage de Microsoft s'exécute dans le navigateur (ancien) ?", answer: "vbscript" },
  { text: "En SQL, quel mot-clé limite le nombre de lignes retournées ?", answer: "limit" },
  { text: "Quelle propriété CSS définit la largeur d'une bordure ?", answer: "border-width" },
  { text: "Quel mot-clé Python importe un module ?", answer: "import" },
  { text: "En React, quel hook évite de recréer une fonction à chaque rendu ?", answer: "usecallback" },
  { text: "Quel format de données est lisible et indenté ?", answer: "yaml" },
  { text: "En base de données, quel mot-clé crée une table ?", answer: "create table" },
  { text: "Quelle méthode JavaScript filtre les éléments d'un tableau ?", answer: "filter" },
  { text: "Quel code HTTP signifie 'erreur serveur interne' ?", answer: "500" },
  { text: "En CSS, quelle propriété ajoute de l'ombre à une boîte ?", answer: "box-shadow" },
  { text: "Quel mot-clé Java permet le polymorphisme ?", answer: "override" },
  { text: "En Git, quelle commande annule des modifications non commitées ?", answer: "restore" },
  { text: "Quelle structure permet d'exécuter du code selon une valeur ?", answer: "switch" },
  { text: "Quel langage fonctionnel s'exécute sur la JVM ?", answer: "scala" },
  { text: "En JavaScript, quelle propriété donne le nombre d'arguments ?", answer: "length" },
  { text: "Quel mot-clé SQL renomme une colonne dans un résultat ?", answer: "as" },
  { text: "En HTML, quelle balise crée un champ de formulaire ?", answer: "input" },
  { text: "Quelle propriété CSS fixe la taille de la police ?", answer: "font-size" },
  { text: "Quel mot-clé Python boucle sur une séquence ?", answer: "for" },
  { text: "En React, quel hook accède au contexte ?", answer: "usecontext" },
  { text: "Quel protocole permet d'envoyer des emails ?", answer: "smtp" },
  { text: "En base de données, quel type stocke une date et heure ?", answer: "timestamp" },
  { text: "Quelle méthode JavaScript réduit un tableau à une valeur ?", answer: "reduce" },
  { text: "Quel design pattern crée un nouvel objet en copiant un prototype ?", answer: "prototype" },
  { text: "En CSS, quelle propriété espace les lignes de texte ?", answer: "line-height" },
  { text: "Quel mot-clé Java lance une exception ?", answer: "throw" },
  { text: "En Python, quelle fonction convertit en entier ?", answer: "int" },
  { text: "Quelle méthode HTTP demande les en-têtes uniquement ?", answer: "head" },
  { text: "Quel outil packe une app JavaScript pour le navigateur ?", answer: "webpack" },
  { text: "En HTML5, quelle balise représente un pied de page ?", answer: "footer" },
  { text: "Quelle propriété CSS affiche un élément en bloc ?", answer: "block" },
  { text: "Quel mot-clé SQL crée un index ?", answer: "create index" },
  { text: "En JavaScript, quel opérateur fusionne des objets (spread) ?", answer: "..." },
  { text: "Quel langage compile en bytecode pour la JVM ?", answer: "kotlin" },
  { text: "En Git, quelle commande fusionne une branche ?", answer: "merge" },
  { text: "Quelle unité CSS vaut 1% de la largeur du parent ?", answer: "%" },
  { text: "Quel symbole en regex représente n'importe quel caractère ?", answer: "." },
  { text: "En React, quel hook gère une référence mutable ?", answer: "useref" },
  { text: "Quel format de données est binaire et compact ?", answer: "msgpack" },
  { text: "En base de données, quel mot-clé supprime une table ?", answer: "drop table" },
  { text: "Quelle méthode JavaScript inverse l'ordre d'un tableau ?", answer: "reverse" },
  { text: "Quel code HTTP signifie 'redirection permanente' ?", answer: "301" },
  { text: "En CSS, quelle propriété décore le texte (souligné, barré) ?", answer: "text-decoration" },
  { text: "Quel mot-clé Java indique une méthode de classe ?", answer: "static" },
  { text: "En Python, quel mot-clé inclut un bloc optionnel après try ?", answer: "else" },
  { text: "Quelle structure de données permet des insertions/suppressions aux deux extrémités ?", answer: "deque" },
  { text: "Quel langage est utilisé pour les requêtes NoSQL sur MongoDB ?", answer: "javascript" },
  { text: "En HTML, quelle balise crée un bouton ?", answer: "button" },
  { text: "Quelle propriété CSS définit la famille de police ?", answer: "font-family" },
  { text: "Quel mot-clé SQL fait une jointure interne ?", answer: "inner join" },
  { text: "En JavaScript, quelle méthode trouve le premier élément qui matche ?", answer: "find" },
  { text: "Quel design pattern sépare l'algorithme de la structure ?", answer: "strategy" },
  { text: "En Git, quelle commande clone un dépôt ?", answer: "clone" },
  { text: "Quel protocole permet de faire du RPC sur HTTP ?", answer: "grpc" },
  { text: "En React, quel hook personnalise la logique réutilisable ?", answer: "custom hook" },
  { text: "Quel type de base de données stocke des paires clé-valeur ?", answer: "redis" },
  { text: "Quelle méthode JavaScript trie les éléments d'un tableau ?", answer: "sort" },
  { text: "Quel code HTTP signifie 'contenu non trouvé' (204) ?", answer: "204" },
  { text: "En CSS, quelle propriété crée une transition ?", answer: "transition" },
  { text: "Quel mot-clé Java empêche l'héritage d'une classe ?", answer: "final" },
  { text: "En Python, quelle fonction retourne la valeur absolue ?", answer: "abs" },
  { text: "Quelle méthode HTTP applique des modifications partielles ?", answer: "patch" },
  { text: "Quel outil exécute des tests JavaScript ?", answer: "jest" },
  { text: "En HTML5, quelle balise lit une vidéo ?", answer: "video" },
  { text: "Quelle propriété CSS fixe la position au défilement ?", answer: "sticky" },
  { text: "Quel mot-clé SQL ajoute une contrainte ?", answer: "constraint" },
  { text: "En JavaScript, quel mot-clé crée une classe ?", answer: "class" },
  { text: "Quel langage est le préprocesseur CSS le plus connu ?", answer: "sass" },
  { text: "En base de données, quel type est un booléen ?", answer: "boolean" },
  { text: "Quelle méthode JavaScript concatène deux tableaux ?", answer: "concat" },
  { text: "Quel design pattern adapte une interface à une autre ?", answer: "adapter" },
  { text: "En Git, quelle commande crée un stash ?", answer: "stash" },
  { text: "Quel symbole en regex signifie 'début de chaîne' ?", answer: "^" },
  { text: "En React, quelle prop permet de passer des enfants ?", answer: "children" },
  { text: "Quel format de logs est structuré en JSON ?", answer: "json" },
  { text: "En SQL, quel mot-clé agrège en somme ?", answer: "sum" },
  { text: "Quelle propriété CSS anime un élément ?", answer: "animation" },
  { text: "Quel mot-clé Python définit un bloc de code optionnel ?", answer: "else" },
  { text: "Quelle structure de données utilise des buckets et un hash ?", answer: "hashmap" },
  { text: "Quel langage sert à écrire des requêtes sur Elasticsearch ?", answer: "json" },
  { text: "En HTML, quelle balise crée une liste ordonnée ?", answer: "ol" },
  { text: "Quelle propriété CSS définit la transparence ?", answer: "opacity" },
  { text: "Quel mot-clé JavaScript lie le this d'une fonction ?", answer: "bind" },
  { text: "En base de données, quel mot-clé crée une vue ?", answer: "create view" },
  { text: "Quel code HTTP signifie 'trop de requêtes' (rate limit) ?", answer: "429" },
  { text: "En CSS, quelle propriété permet flexbox ?", answer: "flex" },
  { text: "Quel mot-clé Java indique une interface ?", answer: "interface" },
  { text: "En Python, quelle méthode ajoute un élément à une liste ?", answer: "append" },
  { text: "Quelle méthode HTTP demande une ressource conditionnelle ?", answer: "get" },
  { text: "Quel outil gère les dépendances Python ?", answer: "pip" },
  { text: "En Git, quelle commande affiche les différences ?", answer: "diff" },
  { text: "Quelle méthode JavaScript inclut un élément dans un tableau ?", answer: "includes" },
  { text: "Quel design pattern crée des familles d'objets liés ?", answer: "abstract factory" },
  { text: "En HTML5, quelle balise représente une section ?", answer: "section" },
  { text: "Quelle propriété CSS définit la marge extérieure ?", answer: "margin" },
  { text: "Quel mot-clé SQL fait une sous-requête ?", answer: "subquery" },
  { text: "En JavaScript, quel opérateur optionnel évite les erreurs sur null ?", answer: "?." },
  { text: "Quel langage typé statiquement compile en natif ?", answer: "rust" },
  { text: "En React, quel concept évite de muter le state directement ?", answer: "immutabilité" },
  { text: "Quel protocole permet de streamer des événements (SSE) ?", answer: "sse" },
  { text: "En base de données, quel type est un nombre décimal ?", answer: "decimal" },
  { text: "Quelle méthode JavaScript supprime le premier élément d'un tableau ?", answer: "shift" },
  { text: "Quel symbole en regex signifie 'fin de chaîne' ?", answer: "$" },
];

export function getPredefinedQuestion(index: number): PredefinedQuestion | null {
  if (index < 0 || index >= PREDEFINED_QUESTIONS.length) return null;
  return PREDEFINED_QUESTIONS[index] ?? null;
}

export function getPredefinedCount(): number {
  return PREDEFINED_QUESTIONS.length;
}
